### PR TITLE
 Abs 86 export import

### PR DESCRIPTION
**Pull request by alan-stokes**
ties into the work of https://github.com/orppst/pst-gui/pull/88 and would need to be merged together.

this covers the taking of the zip and unpacking it and utilising the transactional nature of the database to ensure a clean success / failure. 

this work includes:
1. the proposalUploader which is a class which contains all the logic for reading zip files and creating separate bits of a observation from JSON to database with new ids.
2.  it includes the following sections that are considered incomplete, in that they dont cover all types of subtypes. these are. target (SolarSystemTarget), source coords (RealCartesianPoint, SphericalPoint, GenericPoint, LonLatPoint, CartesianPoint), obversations (CalibrationObservation), observation timing constraints (TimingConstraint, SimultaneityConstraint, PointingConstaint) the entireity of related proposals, and the data type for the different justifications.

The rest of the system works as required. So anything you can see in the UI as it currently stands, is cloned successfully. these have been tested using the attached proposals.

### CODE REVIEW

**Comment by alan-stokes** [comment]
[proposal (17).zip](https://github.com/orppst/pst-api-service/files/14127503/proposal.17.zip)
[proposal (24).zip](https://github.com/orppst/pst-api-service/files/14127505/proposal.24.zip)
 
proposal 17 was a basic proposal with only 1 technical goal, no targets, no observations, no supporting docs. This was to cover any missing data hooks.

proposal 24 was a complete proposal with targets, supporting docs, observations etc.

**Comment by alan-stokes** [comment]
I've also tested with a zip of the forticlient which was 800 MB, obviously that cant be uploaded here. but it was used to verify the size metric was working correctly also.

**Comment by alan-stokes** [comment]
Ive also tested uploading the same proposal 4 times and then changing internals of each and reloading the page and see that the changes only persisted on the changed propsoal. so convinced its working correctly.

**Comment by alan-stokes** [comment]
This is notes for future developers looking in. 
If i was to redo this now. the following would occur.
1. id move the rest request and injects out of the proposal resource and into its own resource to reduce complexities.
2. Id look into getting from the JSONObjects and JSON arrays into an instance of the ObservationProposal first. This would make major changes, given then you wouldnt need to move every little param from one place to another, but you would still need to start with a plain new proposal and then add the items separately. You could likely use methods like "copyMe" which exists on the targetObservation which may allow you to skip more lines as well. 
2.2 the reason why i didnt do it myself, was partly that my minimum attempts at the beginning to get the json to convert resulted in parsing errors and therefore i ditched it for the raw json objects for speed. The other reason is to do it correctly, you will need to validate the json against a schema, which i hadn't had time to look into.
3. Id look into the zip reader for a better approach than iterating around the zip each time looking for the file, but the need to keep the data in  memory instead of on disk meant my experiments with that failed, and i fell back to the iterative search. 
4. As an aside, if you do decide to fiddle with this, i recommend 1 of the following. 1. fix the supporting doc resource so that during start up it clears the doc store from tmp. or 2. omit the lines that stores docs, coz at the moment, it will clash with reboots and drove me a bit nuts near the end.

**Comment by alan-stokes** [comment]
just to add more context, this was the code I orginally started with: 
`import jakarta.json.bind.Jsonb;
import jakarta.json.bind.JsonbBuilder;
try (Jsonb jsonb = JsonbBuilder.create(); ) {
            ObservingProposal newProposal = jsonb.fromJson(
                new String(proposalData), ObservingProposal.class);
            logger.info("proposal json looks like this: ");
            logger.info(newProposal.toString());
            logger.info("proposal json ended");
        } catch (Exception e) {
            logger.error(
                "failed to convert to object with error" + e.getMessage());
            throw new RuntimeException(e);
        }
`

the error that was produced was the following:

2024-02-05 12:58:38,628 ERROR [org.orp.pst.api.res.ProposalUploader] (executor-thread-1) failed to convert to object with errorUnable to deserialize property 'targets' because of: Can't create instance
2024-02-05 12:58:38,629 ERROR [ListenerBean] (executor-thread-1) jakarta.json.bind.JsonbException: Unable to deserialize property 'targets' because of: Can't create instance: java.lang.RuntimeException: jakarta.json.bind.JsonbException: Unable to deserialize property 'targets' because of: Can't create instance
	at org.orph2020.pst.apiimpl.rest.ProposalUploader.uploadProposal(ProposalUploader.java:122)
	at org.orph2020.pst.apiimpl.rest.ProposalResource.uploadProposal(ProposalResource.java:172)
	at org.orph2020.pst.apiimpl.rest.ProposalResource_Subclass.uploadProposal$$superforward(Unknown Source)
	at org.orph2020.pst.apiimpl.rest.ProposalResource_Subclass$$function$$26.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.orph2020.pst.apiimpl.rest.ProposalResource_Subclass.uploadProposal(Unknown Source)
	at org.orph2020.pst.apiimpl.rest.ProposalResource_ClientProxy.uploadProposal(Unknown Source)
	at org.orph2020.pst.apiimpl.rest.ProposalResource$quarkusrestinvoker$uploadProposal_2732998dcc4470b617cfc2a3e8903327fd64e630.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: jakarta.json.bind.JsonbException: Unable to deserialize property 'targets' because of: Can't create instance
	at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:80)
	at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:31)


My first impression after having got this pr up to this point, was that it may have had something to do with the timestamps inside the observation, as it produces a 0.000 instead of a Z which creates the parser for converting to UTC time. This was fixed in the pr with a string replace, but it seems that the error was actually due to something within targets. which is even more suspect. It may be that the "easiest" approach is to stick with this converter and flesh it out fully. But i loath to suggest it, as it is very clunky.

anyhow, food for whomever this lands on.

**Review by DJWalker42 — APPROVED** [review]
This looks fine

**Pull request merged**
